<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ijs</string>
	</array>
	<key>name</key>
	<string>J</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(if|else|elseif|while|for|for_[a-z]+|whilst|do|end)\.</string>
			<key>name</key>
			<string>keyword.control.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(continue|break|return|assert)\.</string>
			<key>name</key>
			<string>keyword.control.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([aAibCeEfFHIjLMor]\.|[aiFLpqsSuxZ]:|[Fp]\.{1,2}|[F][.:]{2})</string>
			<key>name</key>
			<string>support.function.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[_]*[0-9]:</string>
			<key>name</key>
			<string>support.function.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(echo|smoutput)\b|</string>
			<key>name</key>
			<string>keyword.other.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>NB\..+$</string>
			<key>name</key>
			<string>comment.line.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=(\.|:)</string>
			<key>name</key>
			<string>meta.definition.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([*\{\}\-+&amp;#$%@!~`^\[\]\|\,\/\\;"?&lt;&gt;_]\.|\s+\.)</string>
			<key>name</key>
			<string>keyword.operator.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[*\{\}\-+&amp;#$%@!~`^\[\]\|\,\/\\;"?&lt;&gt;:]</string>
			<key>name</key>
			<string>keyword.operator.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([*\{\}\-+&amp;#$%@!~`^\[\]\|\,\/\\;"?&lt;&gt;](?!\)|\{))</string>
			<key>name</key>
			<string>keyword.operator.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(_|_?[0-9]+(\.[0-9]+)?j?_?[0-9]*(\.[0-9]+)?)x?\b</string>
			<key>name</key>
			<string>constant.numeric.j</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([a-zA-Z][a-zA-Z0-9]*)\s*(=[.:])\s*(\{\{\)n).*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.definition.j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.block.j</string>
			<key>end</key>
			<string>.*()()(\}\}).*$</string>
			<key>name</key>
			<string>source.noun.j</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\{\)n)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.block.j</string>
			<key>end</key>
			<string>^(\}\})$</string>
			<key>name</key>
			<string>source.noun.j</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z][a-zA-Z0-9]*)\s*(=[.:])\s*(\{\{)(\)[m,d,v,a,c])*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.definition.j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.function.j</string>
			<key>end</key>
			<string>^()()(\}\})</string>
			<key>name</key>
			<string>source.function.j</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z][a-zA-Z0-9]*)\s*(=[.:])\s*([0-4,13]\s+:\s*0)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.definition.j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.function.j</string>
			<key>end</key>
			<string>^()()(\))</string>
			<key>name</key>
			<string>source.function.j</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.definition.j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z][a-zA-Z0-9]*)\s*(=[.:])\s*([0-4,13]\s+:)\s+'(.+)'</string>
			<key>name</key>
			<string>source.function.j</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.definition.j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z][a-zA-Z0-9]*)\s*(=[.:])\s*(?![0-4,13]|\{\{)</string>
			<key>name</key>
			<string>meta.expression.j</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.language.j</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.line.j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z][a-zA-Z0-9]*)\s+([a-zA-Z][a-zA-Z0-9]+)\s*([^a-zA-Z]*?)\s+([a-zA-Z][a-zA-Z0-9]*)\s+(NB\..*$)*$</string>
			<key>name</key>
			<string>meta.expression.j</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.line.j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z][a-zA-Z0-9]*?)\s*([^a-zA-Z]*?)\s+([a-zA-Z][a-zA-Z0-9]+?)\s+(NB\..*$)*$</string>
			<key>name</key>
			<string>meta.expression.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z][a-zA-Z0-9]*(?!\.)</string>
			<key>name</key>
			<string>variable.language.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.*?'</string>
			<key>name</key>
			<string>string.quoted.single.j</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.j</string>
	<key>uuid</key>
	<string>7E6B46D7-E13D-4100-8C4F-FFC9FB766921</string>
</dict>
</plist>
